apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - services/relp-service.json
  - services/serviceaccount.json
  - services/role.json
  - services/rolebinding.json
  - services/secret.json
  - pods/first-pod.json
  - pods/second-pod.json
  - pods/third-pod.json
  - pods/fourth-pod.json
  - pods/fifth-pod.json
  - pods/k8s_01.json
  - pods/receiver.json
configMapGenerator:
  - name: app-config
    files:
      - config/k8s_01/config.json
      - config/k8s_01/log4j2.xml
  - name: receiver-config
    files:
      - config/rlp_07/log4j2.xml
