# k8s_01

A container that will read mounted container logfiles, then enriches them using Kubernetes API server, and forwards them with RELP to wanted target server.

## Usage

All of the files need to be applied with `kubectl apply -f {filename.json}`

### Service account

Create simple ServiceAccount

[source,json,title="link:example/services/serviceaccount.json[serviceaccount.json]"]
----
include::example/services/serviceaccount.json[]
----

### Role
Create a Role with access to 'pods' and 'namespaces' resources, with verbs 'get', 'watch' and 'list'.

[source,json,title="example/services/role.json"]
----
include::example/services/role.json[]
----

### Role binding

Create Role Binding that contains the service account

[source,json,title="link:example/services/rolebinding.json[rolebinding.json]"]
----
include::example/services/rolebinding.json[]
----

### Service

Create a service for the service account to use

[source,json,title="link:example/services/serviceaccount.json[serviceaccount.json]"]
----
include::example/services/serviceaccount.json[]
----

### Volume mount

Create configMapGenerator called `app-config`, for example in `examples` project:

[source,bash]
----
kubectl create configmap app-config --from-file=example/config/k8s_01/config.json --from-file=example/config/k8s_01/log4j2.xml
----

Reference k8s_01 link:example/config/k8s_01/config.json[config.json]

Reference k8s_01 link:example/config/k8s_01/log4j2.xml[log4j2.xml]

### k8s_01 pod

Make the pod definition use the service account we just made.

[source,json]
----
{
  <snip>
  "spec": {
    "serviceAccount": "kubelogreader",
    "serviceAccountName": "kubelogreader",
    <snip>
  }
}
----

Mount the log containing volumes for runtime processing

[source,json]
----
{
  "spec": {
    <snip>
    "volumes": [
      {
        "name": "app-config",
        "configMap": {
          "name": "app-config"
        }
      },
      {
        "name": "host-var-log-containers",
        "hostPath": {
          "path": "/var/log/containers",
          "type": "Directory"
        }
      },
      {
        "name": "host-var-log-pods",
        "hostPath": {
          "path": "/var/log/pods",
          "type": "Directory"
        }
      },
      {
        "name": "host-var-lib-docker-containers",
        "hostPath": {
          "path": "/var/lib/docker/containers",
          "type": "Directory"
        }
      },
      {
        "name": "host-mnt-statefiles",
        "hostPath": {
          "path": "/mnt/statefiles",
          "type": "DirectoryOrCreate"
        }
      }
    ],
    <snip>
  }
}
----

And also mount those volumes

[source,json]
----
{
  "spec": {
    <snip>
    "containers": [
      <snip>
      "volumeMounts": [
          {
            "mountPath": "/config/",
            "name": "app-config"
          },
          {
            "mountPath": "/var/log/containers",
            "name": "host-var-log-containers",
            "readOnly": true
          },
          {
            "mountPath": "/var/log/pods",
            "name": "host-var-log-pods",
            "readOnly": true
          },
          {
            "mountPath": "/var/lib/docker/containers",
            "name": "host-var-lib-docker-containers",
            "readOnly": true
          },
          {
            "mountPath": "/opt/teragrep/k8s_01/var",
            "name": "host-mnt-statefiles",
            "readOnly": false
          }
        ],
        <snip>
    ]
  }
}
----

And start the k8s_01 image with for example the following arguments. It uses `KUBERNETES_SERVICE_HOST` with `KUBERNETES_SERVICE_PORT` environment variables to find out the API server, and `RELP_SERVICE_PORT_1601_TCP_ADDR` to find the port for the RELP target server.

[source,json]
----
 "command": [
  "/usr/bin/bash"
],
"args": [
  "-c",
  "jq --arg host \"${KUBERNETES_SERVICE_HOST}\" --arg port \"${KUBERNETES_SERVICE_PORT}\" --arg target \"${RELP_SERVICE_PORT_1601_TCP_ADDR}\" '.relp.target=$target | .kubernetes.url=(\"https://\" + $host + \":\" + $port)' /config/..data/config.json > /opt/teragrep/k8s_01/etc/config.json; cd /opt/teragrep/k8s_01 || exit 1; java -Dlog4j2.configurationFile=file:/config/..data/log4j2.xml -jar lib/k8s_01.jar;"
]
----


Full example config:

[source,json,title="link:example/pods/k8s_01.json[example/pods/k8s_01.json]"]
----
include::example/pods/k8s_01.json[]
----

## Example test cluster usage

Read example project in `/example` directory for example usage
