apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelogreader
  namespace: {{.Release.Namespace}}
subjects:
  - kind: ServiceAccount
    name: kubelogreader
    namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: kubelogreader
  apiGroup: rbac.authorization.k8s.io
