apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{.Release.Namespace}}
  name: kubelogreader
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - namespaces
  verbs:
    - get
    - watch
    - list
