image:
  # Image will be downloaded from {repository}/{path}:{Tag from Chart.Version}
  repository: ghcr.io
  path: teragrep/k8s_01
  pullPolicy: IfNotPresent

config:
  # Which port metrics service will be exposed to
  metrics:
    port: 12345
  # Kubernetes configurations
  kubernetes:
    # Base path where logs are read from. Uses {logdir}/{logfiles}
    logdir: /var/log/containers
    # Kubernetes API url where metadata is asked from. Can be dynamically set with "K8S_01_KUBERNETES_URL" environment variable.
    url: https://127.0.0.1:8443
    # Timezone used by the logs
    timezone: Europe/Helsinki
    # How long API responses are cached
    cacheExpireInterval: 900
    # How many api responses are cached
    cacheMaxEntries: 4096
    labels:
      hostname:
        # Hostname to use if label not found
        fallback: fallback-hostname
        # Which label to search for when looking for hostname
        labelStdout: host
        # Which label to search for when looking for hostname for stderr streams. Uses labelStdout if set to null.
        labelStderr: host-stderr
      appname:
        # Appname to use if label not found
        fallback: fallback-appname
        # Which label to search for when looking for appname
        labelStdout: app
        # Which label to search for when looking for appname for stderr streams. Uses labelStdout if set to null.
        labelStderr: app-stderr
      discard:
        # Enable discarding of events when label exists and value is equal to "true", case insensitive
        enabled: false
        # Label to search for
        label: if-found-discard-my-logs
    # Regex for logfiles that are read. Uses {logdir}/{logfiles}
    logfiles:
      - example-pod_default_.*
      - second-pod_default_.*
    # How many threads are spawned for each logfile. One relp connection will be opened for each logfile thread so there are total of len(logfiles)*maxLogReadingThreads relp connections.
    maxLogReadingThreads: 2
  relp:
    # Relp target server. Can be set dynamically with "K8S_01_RELP_TARGET" environment variable.
    target: 127.0.0.1
    # Relp target server port. Can be set dynamically with "K8S_01_RELP_PORT" environment variable
    port: 1601
    # Timeouts and intervals, in milliseconds.
    connectionTimeout: 5000
    readTimeout: 5000
    writeTimeout: 5000
    reconnectInterval: 5000

# Application logging level. For more information, see templates/configmap.yaml and log4j2.xml section
logging:
  level: INFO

# Which namespace it will be installed to.
namespace: teragrep
