apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: {{.Values.namespace}}
data:
  config.json: |-
    {{toJson .Values.config}}

  log4j2.xml: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration monitorInterval="30" status="error">
        <Appenders>
            <Console name="STDOUT">
                <PatternLayout pattern="%d{dd.MM.yyyy HH:mm:ss.SSS} [%level] [%logger] [%thread] %msg%ex%n" />
            </Console>
        </Appenders>
        <Loggers>
            <Logger name="com.teragrep.k8s_01" level="{{.Values.logging.level}}" additivity="false">
                <AppenderRef ref="STDOUT" />
            </Logger>
            <Root level="{{.Values.logging.level}}">
                <AppenderRef ref="STDOUT" />
            </Root>
        </Loggers>
    </Configuration>
