apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: {{.Values.namespace}}
data:
  config.json: |-
    {
      "metrics": {
        "port": {{.Values.config.metrics.port}}
      },
      "kubernetes": {
        "logdir": "/var/log/containers",
        "url": "{{.Values.config.kubernetes.url}}",
        "timezone": "{{.Values.config.kubernetes.timezone}}",
        "cacheExpireInterval": {{.Values.config.kubernetes.cacheExpireInterval}},
        "cacheMaxEntries": {{.Values.config.kubernetes.cacheMaxEntries}},
        "labels": {
          "hostname": {
            "prefix": "{{.Values.config.kubernetes.labels.hostname.prefix}}",
            "fallback": "{{.Values.config.kubernetes.labels.hostname.fallback}}",
            "labelStdout": "{{.Values.config.kubernetes.labels.hostname.labelStdout}}",
            "labelStderr": "{{.Values.config.kubernetes.labels.hostname.labelStderr}}"
          },
          "appname": {
            "prefix": "{{.Values.config.kubernetes.labels.appname.prefix}}",
            "fallback": "{{.Values.config.kubernetes.labels.appname.fallback}}",
            "labelStdout": "{{.Values.config.kubernetes.labels.appname.labelStdout}}",
            "labelStderr":  "{{.Values.config.kubernetes.labels.appname.labelStderr}}"
          }
        },
        "logfiles": {{ toJson .Values.config.kubernetes.logfiles }},
        "maxLogReadingThreads": {{.Values.config.kubernetes.maxLogReadingThreads}}
      },
      "relp": {
        "target": "{{.Values.config.relp.target}}",
        "port": {{.Values.config.relp.port}},
        "connectionTimeout": {{.Values.config.relp.connectionTimeout}},
        "readTimeout": {{.Values.config.relp.readTimeout}},
        "writeTimeout": {{.Values.config.relp.writeTimeout}},
        "reconnectInterval": {{.Values.config.relp.reconnectInterval}}
      }
    }

  log4j2.xml: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration monitorInterval="30" status="error">
        <Appenders>
            <Console name="STDOUT">
                <PatternLayout pattern="%d{dd.MM.yyyy HH:mm:ss.SSS} [%level] [%logger] [%thread] %msg%ex%n" />
            </Console>
        </Appenders>
        <Loggers>
            <Logger name="com.teragrep.k8s_01" level="{{.Values.config.logging.level}}" additivity="false">
                <AppenderRef ref="STDOUT" />
            </Logger>
            <Root level="{{.Values.config.logging.level}}">
                <AppenderRef ref="STDOUT" />
            </Root>
        </Loggers>
    </Configuration>
