apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.json: |-
{{ $.Files.Get "etc/config.json" | indent 4 }}
  log4j2.xml: |-
{{ $.Files.Get "src/main/resources/log4j2.xml" | indent 4 }}
