apiVersion: v1
kind: PersistentVolume
metadata:
  name: statestore-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/teragrep/k8s_01/var"
