apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubelogreader
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kubelogreader
    namespace: default
roleRef:
  kind: Role
  name: kubelogreader
  apiGroup: rbac.authorization.k8s.io
