apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Values.namespace}}
  name: kubelogreader
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - namespaces
  verbs:
    - get
    - watch
    - list
