apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubelogreader
  namespace: {{.Values.namespace}}
subjects:
  - kind: ServiceAccount
    name: kubelogreader
    namespace: {{.Values.namespace}}
roleRef:
  kind: Role
  name: kubelogreader
  apiGroup: rbac.authorization.k8s.io
